version: '3.7'

services:
  web:
    build: .
    container_name: awslogs
    command: >
        bash -c "ls -la && python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8011"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-west-1"
        awslogs-group: "test-aws-log-group"
        awslogs-stream: "test-aws-log-stream"
        awslogs-datetime-format: "%Y-%m-%d %H:%M:%S"
    volumes:
      - .:/django_awslogs_test
    ports:
      - "8011:8011"